name: Vib Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: vanilla-os/vib-gh-action@v0.3.3-1
        with:
          recipe: "vib.yaml"

      - name: Build the Docker image
        run: docker image build -f Containerfile --tag ghcr.io/your_org/your_image:main .
